spring.application.name=voter_management

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/voting?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=root26

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update

# Show SQL Query
spring.jpa.show-sql=true

# Format SQL Query
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
